---

- name: MySQL | Install
  include_tasks: install_{{ mysql_flavour }}.yml
  tags:
    - install

- name: MySQL | Configure
  include_tasks: config.yml
  tags:
    - configure

- name: MySQL | Users
  include_tasks: users.yml
  tags:
    - configure
    - users

- name: MySQL | Databases
  include_tasks: databases.yml
  tags:
    - configure
    - databases

- name: MySQL | Service
  include_tasks: service.yml
  tags:
    - service
