---
- name: MySQL | Set root password
  mysql_user:
    name: "{{ mysql_root_user }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_host: localhost
  when: "installed_mysql.stdout != 'Status: install ok installed'"

- name: MySQL | Ensure MySQL users are present
  mysql_user:
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{  item.priv | default('*.*:USAGE') | join('/') }}"
    append_privs: yes
  with_items: "{{ mysql_users }}"
  no_log: true
